### ISSUE TITLE
How can I use waitForEvent?

### ISSUE THREAD

**Issue by rc0n9027** [lutzseverino/discord-books#4]
ex)
e.getChannel().sendMessageEmbeds(embed).build())
                                        **.setActionRow()**.queue(msg1 -> Server.getEventWaiter().waitForEvent(
                                                ButtonInteractionEvent.class,

**Comment by lutzseverino** [comment]
This seems unrelated to the library, please elaborate further or use #3 if the problem is related.
You might want to refer to the [JDA wiki](https://jda.wiki/introduction/jda/).

**Comment by rc0n9027** [comment]
I want to configure the page in .setActionRow() using discord-books.

**Comment by rc0n9027** [comment]
I want to configure the page in .setActionRow() using discord-books.

**Comment by rc0n9027** [comment]
> This seems unrelated to the library, please elaborate further or use #3 if the problem is related. You might want to refer to the [JDA wiki](https://jda.wiki/introduction/jda/).

I want to configure the page in .setActionRow() using discord-books.

**Comment by lutzseverino** [comment]
You add rows to the book while creating it with the [ref.](https://github.com/lutzseverino/discord-books#adding-component-rows) `#addActionableRows` method. You may also add rows to individual pages.

**Comment by rc0n9027** [comment]
> You add rows to the book while creating it with the [ref.](https://github.com/lutzseverino/discord-books#adding-component-rows) `#addActionableRows` method. You may also add rows to individual pages.

Sorry, I'm not good at English.

I want to use EventWaiter.

```
e.getChannel().sendMessageEmbeds(embed).build())
                                        .queue(msg -> Server.getEventWaiter().waitForEvent(
                                                ButtonInteractionEvent.class,
                                                own-> own.getUser().getId().equals(num),
                                                own-> {
```

Is there any way to override the code?
I want to construct a Page in sendMessageEmbeds.
